### PR TITLE
feat: additions to form

### PR DESCRIPTION
**Pull request by e-lizL**
Additions to form

### CODE REVIEW

**Comment by michael-odonovan** [comment]
Niggles:
- "Future and Sustainability" text needs padding.
- padding on the textarea / "message" box.
- phone number error text isn't red like name field error message.
- message font => have a look at the markup as well as the class => in the markup the tag is a h2, which is forcing h2 styles on the text. There is a hierarchy to CSS styles, with styles that target a specific element (H2) having hier priority than styles that target a class (styled-component).
- have a go at adding &:hover, :active, :focus color styles to the button.
- sort out responsive layout of parent box => form should tuck undo / go vertical on mobile layout. use a @media quiery and change the parent box from flex column to row. or sim.
- Seeing as the Form is a component => put it on the Contact page. Then I think we could even put this site up live : )

**Comment by e-lizL** [comment]
Made the changes. Going to merge the pull request & close now I guess?! xx

**Comment by e-lizL** [comment]
Opps don't think that was right...

**Comment by e-lizL** [comment]
Shall I merge now?

**Comment by e-lizL** [comment]
Merge commit or squash and merge?

**Pull request merged**
